version: '3.8'

services:
  callie-caller-debug:
    build:
      context: .
      dockerfile: Dockerfile.cloudrun-full
      args:
        VERSION: ${VERSION:-1.0.0-debug}
        BUILD_DATE: ${BUILD_DATE}
        VCS_REF: ${VCS_REF}
        BUILD_NUMBER: ${BUILD_NUMBER}
    image: callie-caller-debug:${VERSION:-latest}
    container_name: callie-caller-debug
    restart: unless-stopped
    
    # Load environment from file
    env_file:
      - docker.env
    
    # Additional environment configuration for debugging
    environment:
      # Container-specific settings
      - PYTHONUNBUFFERED=1
      # Force disable UPnP in containers
      - USE_UPNP=false
      # Set container-friendly networking
      - CONTAINER_MODE=true
      # Debug settings
      - LOG_LEVEL=DEBUG
      - DEBUG_AUDIO=true
      - ENABLE_TEST_AUDIO=true
    
    # Port mapping - critical for SIP/RTP
    ports:
      - "${SERVER_PORT:-8080}:8080"
      # SIP signaling port
      - "5060:5060/udp"
      # RTP port range for audio (wider range for container flexibility)
      - "10000-10100:10000-10100/udp"
    
    # Volume mounts
    volumes:
      # Persistent storage for logs and recordings
      - callie_logs_debug:/app/logs
      - callie_audio_debug:/app/captured_audio
      # Mount the debug script
      - ./main-cloudrun-full-debug.py:/app/main-cloudrun-full-debug.py:ro
      # Optional: Mount config file if needed
      - ./docker.env:/app/.env:ro
    
    # Network configuration - use host network for better SIP compatibility
    network_mode: "bridge"
    
    # DNS configuration for better SIP resolution
    dns:
      - 8.8.8.8
      - 1.1.1.1
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Resource limits (adjust based on needs)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Enhanced logging for debugging
    logging:
      driver: "json-file"
      options:
        max-size: "50m"  # Larger logs for debugging
        max-file: "10"   # More log files
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Use debug entry point
    command: ["python", "main-cloudrun-full-debug.py"]

# Named volumes for persistent data
volumes:
  callie_logs_debug:
    driver: local
  callie_audio_debug:
    driver: local 